import * as React from 'react';
import Document, { Html, Head, Main, NextScript, DocumentContext, DocumentInitialProps } from 'next/document'

// @ts-ignore

import outputcss from '!raw-loader!../styles/output.css';


// Import the raw CSS file as a string

export default class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext): Promise<DocumentInitialProps> {
    const originalRenderPage = ctx.renderPage;

    originalRenderPage({
      enhanceApp: (App: any) => (props) => <App {...props} />,
    });
		const initialProps = await Document.getInitialProps(ctx);
    return {
          ...initialProps,
          // styles: [...React.Children.toArray(initialProps.styles)],
          styles: (
            <>
              {process.env.NODE_ENV === 'production' ? (
                <>
                  {initialProps.styles}
                  <style
                    dangerouslySetInnerHTML={{
                      __html: outputcss,
                    }}
                  />
                </>
              ) : (
                [...React.Children.toArray(initialProps.styles)]
              )}
            </>
          ),
        };
      }
  render() {
    return (
      <Html data-ampdevmode>
        <Head>
          <meta name="title" content="Create Next App" />
          <meta name="description" content="Generated by create next app" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}